check if its a scoping issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -79,7 +79,20 @@ jobs:
 
             echo "Commit range: $COMMIT_RANGE"
 
-            bash scripts/dev-release.sh
+            for ORB in src/*/; do
+              orbname=$(basename $ORB)
+              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$orbname") ]]; then
+                (ls ${ORB}orb.yml && echo "orb.yml found, attempting to publish...") || echo "No orb.yml file was found - the next line is expected to fail."
+                if [ -z "$CIRCLECI_API_TOKEN" ]; then
+                  circleci orb publish ${ORB}orb.yml circleci/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
+                else
+                  circleci orb publish ${ORB}orb.yml circleci/${orbname}@dev:${CIRCLE_BRANCH}-${CIRCLE_SHA1} --token $CIRCLECI_API_TOKEN
+                fi
+              else
+                echo "${orbname} not modified; no need to promote"
+              fi
+              echo "---------------------------"
+            done
 
   trigger-downstream:
     machine: true
